# Generated by Django 3.2.3 on 2021-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
