# Generated by Django 3.2.3 on 2021-07-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0006_comment_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avg_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plants.plant')),
            ],
        ),
    ]
