# Generated by Django 3.2.3 on 2021-07-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0007_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='avg_rating',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name={'size__avg': 24.666666666666668}),
        ),
    ]
