# Generated by Django 3.2.3 on 2021-07-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0008_avg_rating_avg_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avg_Rating',
        ),
    ]
