# Generated by Django 3.2.3 on 2021-07-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0009_delete_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='plant',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Plants.comment'),
        ),
    ]
