# Generated by Django 3.2.3 on 2021-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0011_alter_comment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
