# Generated by Django 3.2.3 on 2021-07-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0014_auto_20210709_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='myuser',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_reported',
        ),
    ]
